### ISSUE TITLE
incorrect modal id

### ISSUE THREAD

**Issue by wellrus** [harmyderoman/vuejs-confirm-dialog#10]
repro:

try to show several modal

<button class="btn btn-secondary" @click="reveal();reveal2();">12</button>

Expected
modal  will close one by one

Actual:
All modal have the some id, and close the first

**Comment by harmyderoman** [comment]
Very strange bug, it shouldn't work like that. I will work on it.
In general, this is not designed to call modal windows at the same time.
May I ask in what real cases it may be necessary to call several dialogs at the same time?

**Comment by harmyderoman** [comment]
fixed

**Comment by wellrus** [comment]
Sequential generation is more better solution than randomization.

**Comment by harmyderoman** [comment]
Can you write how you see it?

**Comment by harmyderoman** [comment]
@wellrus I am thinking to use [nanoId](https://github.com/ai/nanoid) for this. Is this will be better solution?

**Comment by wellrus** [comment]
IMHO
you must do it more simple


example:
```
let dialogSequense = 0;

getDialogId() {
    return ++dialogSequense;
}

export const createConfirmDialog = function () {
 const DIALOG_ID = getDialogId()
}
```

**Comment by harmyderoman** [comment]
implemented
