### ISSUE TITLE
Cancel manually?

### ISSUE THREAD

**Issue by robinsandstrom** [harmyderoman/vuejs-confirm-dialog#13]
Is there anyway to cancel the dialog manually?

```
const dialog = createConfirmDialog(h(ModalDialog, { class: 'w-64' }, [h(LoadingSpinner)]))
dialog.reveal()
/*** Some API Calls***/
dialog.cancel()
```

**Comment by harmyderoman** [comment]
No, but I think you can pass the function with all API calls to the Loader component and call it inside Loader and return the data on `confirm` emitting.

**Comment by harmyderoman** [comment]
For example. Your loading component will look like this:
```
// Loader.vue
<template>
  <h1>Loading...</h1>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'

const emit = defineEmits(['confirm', 'cancel'])

const { process } = defineProps({
  process: {
    type: Function
  }
})

onMounted(async () => {
    const data = await process()
    emit("confirm", data)
})
</script>
```

And you can use it like this:
```
import Loader from './components/Loader.vue'
import { createConfirmDialog } from 'vuejs-create-dialog'

const loader = createConfirmDialog(Loader)

// Make function with your api calls
const apiCall = () => {

  // Here go your API Call, I tested it with promise
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve('foo')
    }, 3000)
  })
}

// Call the Loader
loader.reveal({ process: apiCall })

// get back your data
loader.onConfirm((data) => {
  console.log(data) // you will see 'foo' in console
})

```

**Comment by harmyderoman** [comment]
it may seem like a lot of boilerplate code is written, but the advantage of this approach is that you can make a composable function and use it everywhere in your app.
See [useLoader](https://github.com/harmyderoman/vuejs-confirm-dialog/blob/main/demos/vue3/composables/useLoader.ts)

**Comment by harmyderoman** [comment]
`destroy` it's just `cancel`

**Comment by harmyderoman** [comment]
In the case of Loader, you actually don't want to close it on click outside. I personally prefer this:
```
// Modal.vue
<div class="modal-bg" @click.self="emit('cancel')">
...
</div>
```
Maybe I will make `createConfirmDialog` return also `cancel` and `confirm`. `destroyAll` seems like a helpful function if you need to close all alerts. I will think about it. Maybe in the next update, I will add it.

**Comment by harmyderoman** [comment]
@robinsandstrom  I decided to accept your suggestion, but rename `destroy` to `close`, since this function does not really destroy anything and the dialog can be reused again. Also, make `createConfirmDialog ` return `confirm` and 'cancel`.
