### ISSUE TITLE
confirmModal inside other modal; broken ESC functionality if <DialogsWrapper /> is added at the end of main App.vue

### ISSUE THREAD

**Issue by erip2** [harmyderoman/vuejs-confirm-dialog#25]
Using the library with HeadlessUI, and adding the main `<DialogsWrapper />` at the end of the main `App.vue` file breaks the `ESC` functionality. This happens when the confirm modal is opened with a button inside another modal.

This is the codesandbox for reference: https://codesandbox.io/s/vuejs-confirm-dialog-esc-example-luxigt

A reference from HeadlessUI repo: https://github.com/tailwindlabs/headlessui/issues/426#issuecomment-824747388

Thank you!

**Comment by harmyderoman** [comment]
As Robin noticed in the HeadlessUI repo issue, there are 2 options to solve it:
1. Only have 1 open Dialog at the same time. So you just need to modify your `openConfirm` method like this:
```
    openConfirm: function () {
      this.closeModal()
      const dialog = createConfirmDialog(ConfirmModal)

      dialog.onConfirm(() => {
        alert("confirmed");
      })

      dialog.onCancel(() => {
        this.openModal()
      })

      dialog.reveal()
    },
```

**Comment by harmyderoman** [comment]
2. Use nested dialogs. I don't think that way works the same for Vue as for React. I tried to implement this with `Teleport` but I didn't succeed.

**Comment by harmyderoman** [comment]
3. If you still need two dialogs to be open, try to look for an API option that allows you to block the `esc` functionality on the first modal when the second one is open, and unblock on close.

**Comment by erip2** [comment]
Thanks for the detailed answers.

I'm currently going with the second solution; adding `<DialogsWrapper />` inside modals. Not ideal, but it's the best option for our project.

Third solution would be good to, but the Headless UI doesn't have any API to disable the `escape` functionality.

**Comment by harmyderoman** [comment]
@erip2 can you provide your solution?
