### ISSUE TITLE
How to use templates/slots in component used

### ISSUE THREAD

**Issue by chuntin** [harmyderoman/vuejs-confirm-dialog#26]
How to use component slots when use createConfirmDialog(ModalDialog)?

Ex:
`
// ModalDialog.vue
<template>
<slot name="slot1"></slot>
</template>
 `

`
// component where use createConfirmDialog
...
const {reveal...} =createConfirmDialog(ModalDialog, props) // how to inject <template #slot1>Potato chips</template>
`

**Comment by harmyderoman** [comment]
There is no way for this now.  Maybe it will be implemented in the future.

**Comment by chuntin** [comment]
ok, but it looks like a good update. Thanks for de code!

**Comment by harmyderoman** [comment]
Let's leave this issue open; maybe someone wants to implement this.
