### ISSUE TITLE
Dialog doesn't show in my application

### ISSUE THREAD

**Issue by john-** [harmyderoman/vuejs-confirm-dialog#27]
Hello,

I have attempted to incorporate ConfirmDialog into my application.  I am converting the existing Vuetify v-dialog to ConfirmDialog.

Step 0
```
npm view vuejs-confirm-dialog version
0.5.0
```

Step 1
[main.ts](https://gitlab.com/john---/photo_manager/-/blob/confirm_dialog/frontend/src/main.ts)

Step 2
[App.vue](https://gitlab.com/john---/photo_manager/-/blob/confirm_dialog/frontend/src/App.vue#L145)

Using it
It never returns from this and does not show the dialog
[Folders.vue](https://gitlab.com/john---/photo_manager/-/blob/confirm_dialog/frontend/src/components/Folders.vue#L23)

I am probably making a beginners mistake as I am a novice with javascript/typescript.  What is a good next step to figure out what is wrong?

**Comment by john-** [comment]
I am going to pursue using a different approach for doing dialogs with Vuetify so closing this ticket.

**Comment by harmyderoman** [comment]
I think it works, but you didn't see it, because you forgot to add styles to modal

**Comment by john-** [comment]
Thanks.  I will take a look at that!

**Comment by harmyderoman** [comment]
@john- Also you can combine Vuetify and this package. Because this package is not about how to build modals, it's about scaling. you can write your modal component using Vuetify and convert it to a composable function using this package and use it all across your project.

**Comment by john-** [comment]
That is a good point.  I am going down the path of continuing to use Vuetify v-dialog but breaking the modals out into their own .vue file.

In this process my first pass has all sorts of code to define emits to be called by parent and refs to be passed to the child.  It is especially confusing to me to nest dialogs.  Once I am through doing that I will look at composable functions to see how I can improve things.

Thanks for your assistance!

**Comment by john-** [comment]
> I think it works, but you didn't see it, because you forgot to add styles to modal

This looks like it was the problem.  I added styles from one of the example dialogs and something now appears in my basic (non-Vuetify) dialog.

I am such a novice at this as it was the first time something didn't display for me without styles.  Usually something ugly shows up at least :)

I will convert it over to vuetify components as a next step.

**Comment by john-** [comment]
I went down the path of converting the dialog to Vuetify rendering.  It worked for bit and some change I made broke it.  By this I mean the dialog did not display...in the same way when there were no styles.

So I started over again and cannot get a dialog to display.  Here is the current version:
```
<script setup lang="ts">
  const emit = defineEmits(['confirm', 'cancel'])
</script>

<template>
  <div class="my-modal">
    <!-- The modal component body -->
    <button @click="emit('confirm')">Confirm</button>
    <button @click="emit('cancel')">Cancel</button>
  </div>
</template>

<style>
.my-modal {
  display: flex;
  align-items: center;
  justify-content: center;
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: #cecece89;
  transition-property: background-color, border-color, color, fill, stroke,
    opacity, box-shadow, transform;
  transition-duration: 0.15s;
  transition-duration: 0.2s;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  z-index: 100;
}
</style>
```
The `<style>` section was something I copied and pasted from one of the confirm-dialog examples.

Is there some basic style I can apply that will for sure show a dialog if all other things are done correctly?  I don't care what it looks like I just want to see the two buttons.

**Comment by john-** [comment]
That would be really helpful.

I will still keeping working on this as I am not sure if the problem I am experiencing is due to something specific in my environment.

**Comment by john-** [comment]
Your code worked for me and thanks for sharing it.

I had been way off base with how I was integrating Vuetify.  Your example makes that clear to me now.

Also, if I leave the `<div>` tag out it still renders correctly (no change before or after for me).

Thanks again!

**Comment by john-** [comment]
Closing ticket as my problem has been addressed.
