### ISSUE TITLE
Where to put dialog logic

### ISSUE THREAD

**Issue by john-** [harmyderoman/vuejs-confirm-dialog#28]
I am converting over dialogs using "native" Vuetify v-dialog to wrapping them with vuejs-confirm-dialog.

Currently if user clicks Confirm the .vue file that contains the dialog `<template>` also has logic in its `<script>` section.  This does things like use Axios to interact with server based api.

In going through the vuejs-confirm-dialog examples and demo it seems like that logic is in the component that called the dialog and not in the dialog itself.  Any data needing to be processed is sent back to the component that called the dialog.  Is this the proper approach?

I have been trying to perform the logic in the dialog in advance of the `emit('confirm')` but getting error.  As this may not be correct approach I thought I was ask first.

**Comment by john-** [comment]
It looks like error I was getting was due to problem with my code and not related to where logic goes.  Closing this ticket for now.

**Comment by harmyderoman** [comment]
Yes, this is the correct approach to use in this case and always in Vue applications, so you can reuse the basic components regardless of the situation's logic.
