### ISSUE TITLE
How to get the dialog reference

### ISSUE THREAD

**Issue by Kevinrp22** [harmyderoman/vuejs-confirm-dialog#30]
Is it possible to get the modal reference from the component where the createConfirmDialog function is used?

something like this: 

```vue

//CustomDialog.vue

<template>
    // i need this dialog reference
    <Dialog >
</template>

 ```
```vue

//Any component that use confirmDialog, e.g: App.vue
<template>
  // some code here...
</template>
 
<script setup>
import CustomDialog from './components/SimpleDialog.vue'
import { createConfirmDialog } from 'vuejs-confirm-dialog'
import { ref } from 'vue'

const dialogReference = ref()

const { reveal, onConfirm } = createConfirmDialog(CustomDialog, { question: 'Are you sure?', ref:dialogReference})
 
onConfirm(() => {
  // some code...
})
 ```
 
 It has occurred to me to do it with props but I don't know if it's possible.
 
 In summary: for example in App.vue I need to save the dialog reference in dialogReference.

**Comment by harmyderoman** [comment]
Of course, you can pass data from the modal to the component where you call it. Check [https://vcd-docs.netlify.app/guide/passing-props-and-data#passing-data](Docs)

**Comment by Kevinrp22** [comment]
> Por supuesto, puede pasar datos del modal al componente donde lo llama. Consulte [https://vcd-docs.netlify.app/guide/passing-props-and-data#passing-data](Docs)

Yes, I am passing props like in the example, what happens is that while passing the reference by props to the dialog, I am not able to access/control it from where I use the commit function.

**Comment by Kevinrp22** [comment]
> > Por supuesto, puede pasar datos del modal al componente donde lo llama. Consulte [https://vcd-docs.netlify.app/guide/passing-props-and-data#passing-data](Docs)
> 
> Yes, I am passing props like in the example, what happens is that while passing the reference by props to the dialog, I am not able to access/control it from where I use the commit function.

My problem is that I am using the OnClickOutside function from the VueUse library, I have my modals and everything works correctly, what happens is that in a modal I have a delete button and when I call the function to confirm the action, by giving it to cancel or out of the modal the first modal is closed. According to the vueuse library, I need to pass the references that it has to "ignore" when clicking outside the modal.

**Comment by harmyderoman** [comment]
It will not work, even if you pass the `ref`. Because you need to ignore click outside if the second dialog is open.
This is the solution:
``` 
// FirstModal.vue
const { isRevealed } = createConfirmDialog(CustomDialog)

onClickOutside(target, () => {
  if(!isRevealed.value) {
     emit('cancel')
  }
})
```

**Comment by Kevinrp22** [comment]
I was thinking of doing it with the ref so that from my component hierarchy I can access that dialog with $refs.myConfirmDialog, and so it doesn't matter how nested the component that uses the confirmation box is. 

If I do it as you say, it involves me doing emits and watchers to move 'isReveleaded' to its parents. 

I'm currently using 'ignoreRefs' with some components with no problem, why won't using the reference in the confirmation box work?

**Comment by Kevinrp22** [comment]
Basicamente tengo algo parecido a esto:
 
```vue 
// App.vue
<BaseModal :isOpen=" wtgTypeList.isOpen " :onClose=" wtgTypeList.onClose " :ignore-el-refs=" [wtgTypeFormModal] ">
    <BaseModalHeader>WTG Type List</BaseModalHeader>
    <BaseModalCloseButton />
    <BaseModalBody>
        <ItemList></ItemList>
    </BaseModalBody>
</BaseModal>
```

```vue 
//ItemList.vue

import { confirm } from '@/composables/useConfirm';

<Table>
    <TableHeadings>
        <TableItemHeading>Name</TableItemHeading>
    <TableList v-for="item in itemList" :key="item.id">
        <TableItemList>
           {{ item.name }}
        </TableItemList>
        <TableItemList tools>
            <Button @click="async () => {
                await confirm({
                    type: 'ELIMINATION',
                    onConfirm: async () => await removeItem(item.id),
                })
            }" />
        </TableItemList>
    </TableList>
</Table>
```

If I have to get `isRevealed` in `ItemList`, I have to `watch` it with an `emit` every time its state changes, then App would have to read that emit and save it to a local ref again.

So I wanted to just get the reference from the confirm modal and pass it to `ignore-el-refs`

**Comment by harmyderoman** [comment]
Still, ignoring refs will not work, because you're clicking outside of these refs. But you can still use my solution. Just call `useConfirm` in `App.vue`, and pass `confirm` to `ItemList.vue` as emit

**Comment by harmyderoman** [comment]
Also, you should change your confirm function to use it like this:

```
import { useConfirm } from '@/composables/useConfirm';

const { confirm, isRevealed } = useConfirm()
``

**Comment by Kevinrp22** [comment]
ok, right now I do that and it works for me, if there is no other solution then I will continue using that way, thank you!
