### ISSUE TITLE
NOt installable

### ISSUE THREAD

**Issue by ericlaaper** [harmyderoman/vuejs-confirm-dialog#33]
HI, used your solution in several projects. Working on a new Nuxt project I can't install it anymore.  Got a lot off peer dependencies which are newer. Maybe it's time for an update? 
I made my own sultion using vueUse useConfirmDialog. Which is working well. But your project was much more easier. 

Thanks for the good work.

Cheers,

Eric

**Comment by harmyderoman** [comment]
Could you give me more details for reproduction? It works fine for me, but I import the wrapper manually. My code:

```HTML
// app.vue 
<template>
  <div>
    <button @click="reveal">Click me</button>
    <DialogsWrapper />
  </div>
</template>

<script setup>
import { DialogsWrapper } from 'vuejs-confirm-dialog'
import ModalDialog from '@/components/ModalDialog.vue'
import { createConfirmDialog } from 'vuejs-confirm-dialog'

const { reveal, onConfirm, onCancel } = createConfirmDialog(ModalDialog)

onConfirm(() => {
  console.log('Confirmed!')
})
onCancel(() => {
  console.log('Canceled!')
})
</script>
```

**Comment by harmyderoman** [comment]
@ericlaaper did you solve your problem?
